version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9090:8000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_DATABASE: clothing_db
      DB_USERNAME: clothing_user
      DB_PASSWORD: clothing_password

  db:
    image: mysql:8.0
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: clothing_db
      MYSQL_USER: clothing_user
      MYSQL_PASSWORD: clothing_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
